# https://taskfile.dev

version: '3'

tasks:
  default:
    cmds:
      - task: run

  new:
    desc: "Create a new day project."
    cmds:
      - bash scripts/new.sh

  commit:
    desc: "Commit the latest day solution."
    cmds:
      - bash scripts/commit.sh

  test:
    desc: "Run all unit tests."
    cmds:
      - cargo test

  run:
    desc: "Run all day's solution or a selected one by passing the number of the day."
    cmds:
      - bash scripts/run.sh {{.CLI_ARGS}}